flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- GLURaw-1.5.0.3
- GLUT-2.7.0.11
- ObjectName-1.1.0.1
- OpenGL-2.13.1.0
- OpenGLRaw-2.5.5.0
- gloss-1.10.2.5
- gloss-rendering-1.10.3.5
- wx-0.92.2.0
- wxc-0.92.2.0
- wxcore-0.92.2.0
- wxdirect-0.92.2.0
resolver: lts-3.5
